baseURL: "https://pf711-dev.github.io/"
languageCode: "zh-cn"
title: "pf711's Blog"
theme: "mini"

# 确保这些基本路径配置正确
contentDir: "content"
layoutDir: "layouts"
publishDir: "public"
staticDir: "static"

# 主题配置
params:
  title: "pf711's Blog"
  subtitle: "write what you think..."
  
  # 功能控制
  hiddenPostSummaryInHomePage: true
  showToc: true
  showPowerBy: false
  
  # 导航标签翻译
  navigation:
    - name: "首页"
      url: "/"
    - name: "归档"
      url: "/archive"
    - name: "标签"
      url: "/tags"
    - name: "关于"
      url: "/about"

  # 主要内容区域
  mainSections:
    - "posts"

  baiduAnalytics: "b6502581a21266446d68636064e5431c"
  googleAnalytics: "G-S7VJCRNLF6"  # 通常是以 G- 或 UA- 开头

  # Waline 配置
  waline:
    enable: true
    serverURL: "https://waline-comment-phi-six.vercel.app"
    lang: "zh-CN"
    dark: "auto"
    login: "disable"
    pageview: true
    comment: true
    placeholder: "说点什么吧..."

# Markdown 渲染配置
markup:
  goldmark:
    renderer:
      unsafe: true

# 错误处理
ignoreErrors: ['error-remote-getjson']
ignoreLogs: ['warning-goldmark-raw-html']

menu:
  main:
    - identifier: archive
      name: 归档
      url: /archive/
      weight: 20




